log4j.rootLogger=info, stdout
log4j.logger.Exposed=debug, stdout
log4j.additivity.Exposed=false
log4j.logger.com.zaxxer.hikari.pool.HikariPool=debug, stdout
log4j.additivity.com.zaxxer.hikari.pool.HikariPool=false
log4j.logger.org.jetbrains.exposed.sql.transactions.experimental.SuspendedKt=debug, stdout
log4j.additivity.org.jetbrains.exposed.sql.transactions.experimental.SuspendedKt=false

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.encoding=UTF-8
